services:
  - type: web
    name: telegram-mpesa-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8569971585:AAEBW_I71bEAzapt72vEWaNe_FU9h4lpxQ0
      - key: MPESA_CONSUMER_KEY
        value: Cs3WvBlkb56vVUGwgLGTOqNde9SdXnk6XM7oHTPYD9WMEK6N
      - key: MPESA_CONSUMER_SECRET
        value: IBOOKUbOqXG1Xk7rm09JE9L0WxxCHFApQpYcxKR8zld9Ha2LLlGMyH9LIh53sa0i
      - key: MPESA_PASSKEY
        value: bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
      - key: MPESA_BUSINESS_SHORTCODE
        value: "3131916"
      - key: MPESA_CALLBACK_URL
        value: https://premium-bots.onrender.com/mpesa-callback
      - key: WEBHOOK_URL
        value: https://premium-bots.onrender.com
